import { Crypto, Crypto2, Crypto3, Crypto4 } from "../assets";

export const blockchainVideos = [
  {
    id: 1,
    title: "Introduction to Blockchain Technology",
    description:
      "Learn the fundamentals of blockchain, how it works, and why it matters.",
    educator: "Jane Doe",
    category: "Blockchain Basics",
    language: "English",
    thumbnail: Crypto,
    duration: "15:23",
    views: 1023,
    uploadedAt: "2024-03-12",
    verified: true,
  },
  {
    id: 2,
    title: "Smart Contracts Explained",
    description:
      "A simple breakdown of smart contracts and their real-world applications.",
    educator: "John Smith",
    category: "Smart Contracts",
    language: "Spanish",
    thumbnail: Crypto2,
    duration: "10:45",
    views: 874,
    uploadedAt: "2024-02-28",
    verified: true,
  },
  {
    id: 3,
    title: "Decentralized Finance (DeFi) 101",
    description:
      "Understand the concept of DeFi and how it’s changing traditional finance.",
    educator: "Sarah Johnson",
    category: "DeFi",
    language: "English",
    thumbnail: Crypto3,
    duration: "22:01",
    views: 1450,
    uploadedAt: "2024-01-20",
    verified: false,
  },
  {
    id: 4,
    title: "Understanding Crypto Wallets",
    description:
      "Explore different types of crypto wallets and how to keep your assets secure.",
    educator: "Ali Musa",
    category: "Wallets",
    language: "Arabic",
    thumbnail: Crypto4,
    duration: "18:15",
    views: 432,
    uploadedAt: "2024-04-01",
    verified: true,
  },
  {
    id: 5,
    title: "NFTs and the Future of Ownership",
    description:
      "Dive into NFTs, how they work, and their role in the digital economy.",
    educator: "Emily Zhao",
    category: "NFTs",
    language: "Chinese",
    thumbnail: Crypto2,
    duration: "16:40",
    views: 1203,
    uploadedAt: "2024-03-10",
    verified: false,
  },
  {
    id: 6,
    title: "What is Web3?",
    description:
      "Discover the evolution of the internet with Web3 and its implications.",
    educator: "Victor Eze",
    category: "Web3",
    language: "English",
    thumbnail: Crypto,
    duration: "12:30",
    views: 690,
    uploadedAt: "2024-02-10",
    verified: true,
  },
  {
    id: 7,
    title: "Storing Data on the Blockchain",
    description:
      "A look into decentralized storage and its benefits over traditional storage.",
    educator: "Anna Lee",
    category: "Data Storage",
    language: "Korean",
    thumbnail: Crypto4,
    duration: "14:22",
    views: 324,
    uploadedAt: "2024-03-18",
    verified: false,
  },
  {
    id: 8,
    title: "Proof of Work vs Proof of Stake",
    description:
      "Compare two major consensus mechanisms and how they secure blockchains.",
    educator: "Carlos Diaz",
    category: "Consensus",
    language: "Spanish",
    thumbnail: Crypto3,
    duration: "11:59",
    views: 810,
    uploadedAt: "2024-01-25",
    verified: true,
  },
  {
    id: 9,
    title: "Blockchain in Education",
    description:
      "Explore how blockchain can transform educational systems and record-keeping.",
    educator: "Fatima Bello",
    category: "Use Cases",
    language: "French",
    thumbnail: Crypto,
    duration: "19:45",
    views: 230,
    uploadedAt: "2024-02-14",
    verified: false,
  },
  {
    id: 10,
    title: "Tokenomics for Beginners",
    description:
      "An overview of how tokens are designed, distributed, and used in crypto systems.",
    educator: "Liam Wilson",
    category: "Tokenomics",
    language: "English",
    thumbnail: Crypto4,
    duration: "13:37",
    views: 980,
    uploadedAt: "2024-03-30",
    verified: true,
  },
  {
    id: 11,
    title: "Layer 1 vs Layer 2 Solutions",
    description:
      "Learn the differences between base and scaling blockchain protocols.",
    educator: "Monica Reyes",
    category: "Scalability",
    language: "English",
    thumbnail: Crypto3,
    duration: "17:30",
    views: 764,
    uploadedAt: "2024-03-02",
    verified: true,
  },
  {
    id: 12,
    title: "How DAOs Work",
    description:
      "Understand how Decentralized Autonomous Organizations are structured and governed.",
    educator: "Nina Patel",
    category: "DAOs",
    language: "Hindi",
    thumbnail: Crypto,
    duration: "21:05",
    views: 340,
    uploadedAt: "2024-01-18",
    verified: false,
  },
  {
    id: 13,
    title: "Intro to Solidity Programming",
    description:
      "Start coding smart contracts with Solidity in this hands-on introduction.",
    educator: "Michael Chen",
    category: "Solidity",
    language: "Chinese",
    thumbnail: Crypto3,
    duration: "26:10",
    views: 1554,
    uploadedAt: "2024-03-15",
    verified: true,
  },
  {
    id: 14,
    title: "Blockchain and Identity Verification",
    description:
      "Explore how blockchain can secure digital identity in a decentralized way.",
    educator: "Aisha Muhammad",
    category: "Security",
    language: "Swahili",
    thumbnail: Crypto,
    duration: "20:00",
    views: 486,
    uploadedAt: "2024-02-05",
    verified: true,
  },
  {
    id: 15,
    title: "Building DApps with React & Web3.js",
    description:
      "Step-by-step guide to creating decentralized apps using React and Web3.",
    educator: "David Green",
    category: "Development",
    language: "English",
    thumbnail: Crypto4,
    duration: "28:33",
    views: 1340,
    uploadedAt: "2024-03-22",
    verified: true,
  },
  {
    id: 16,
    title: "Zero-Knowledge Proofs (ZKP) Explained",
    description:
      "Learn how ZKPs provide privacy without compromising verification.",
    educator: "Chinedu Okafor",
    category: "Privacy",
    language: "Igbo",
    thumbnail: Crypto2,
    duration: "16:55",
    views: 275,
    uploadedAt: "2024-04-01",
    verified: false,
  },
  {
    id: 17,
    title: "Interoperability Between Blockchains",
    description:
      "How different blockchain networks can communicate and share data.",
    educator: "Olivia Park",
    category: "Interoperability",
    language: "Korean",
    thumbnail: Crypto3,
    duration: "14:48",
    views: 603,
    uploadedAt: "2024-02-20",
    verified: true,
  },
  {
    id: 18,
    title: "Creating Your First Crypto Token",
    description: "Walkthrough of deploying a custom crypto token on Ethereum.",
    educator: "Leonardo Rossi",
    category: "Token Creation",
    language: "Italian",
    thumbnail: Crypto,
    duration: "23:12",
    views: 923,
    uploadedAt: "2024-01-29",
    verified: true,
  },
  {
    id: 19,
    title: "Exploring Blockchain Use Cases",
    description:
      "Discover industries where blockchain is making a real impact.",
    educator: "Grace Kim",
    category: "Use Cases",
    language: "English",
    thumbnail: Crypto4,
    duration: "18:00",
    views: 745,
    uploadedAt: "2024-03-08",
    verified: false,
  },
  {
    id: 20,
    title: "Intro to Blockchain for Beginners",
    description:
      "A friendly and simple start for anyone curious about blockchain.",
    educator: "Samuel Adeyemi",
    category: "Beginner",
    language: "Yoruba",
    thumbnail: Crypto2,
    duration: "11:11",
    views: 567,
    uploadedAt: "2024-04-01",
    verified: true,
  },
];
